### ISSUE TITLE
сделать расчет в новой функции скважины через удлинение

### ISSUE THREAD

**Issue by khabibullinra** [unifloc/unifloc_vba#33]
сделать возможность задания конструкции скважины через измеренную глубину и удлинение для обеспечения возможности массовых расчетов с тех режимом
для этого надо придумать как передавать параметр удлинения в расчетную функцию

**Comment by khabibullinra** [comment]
наверное логично будет сделать такие варианты 
1. если одно число - то это вертикальная скважина и ее глубина
2. если два числа - то это измеренная глубина и вертикальная
3 если массив из двух столбцов - то это инклинометрия

**Comment by KhalikovRuslan** [comment]
Для массовых расчётов тех режима возможно будет полезно брать 3 параметра удлинения:
1) На глубину верхних дыр перфорации;
2) На глубину спуска оборудования;
3) На глубину динамического уровня.
Они как правило указываются там.

Если их отличать, то например расчёт Рпр от Ндин станет немного точнее

**Comment by khabibullinra** [comment]
сделано в варианте что можно задать два числа - измеренную и вертикальную глубину и все сработает как надо
