### ISSUE TITLE
Расчет давления насыщения

### ISSUE THREAD

**Issue by kobzarius** [unifloc/unifloc_vba#34]
![image](https://user-images.githubusercontent.com/43096418/75559483-99a98d80-5a54-11ea-85a7-37871c17f8ac.png)

в функции calc_PVT нет присвоения атрибуту рассчитанного значения давления насыщения

только
pb_calc_atma_ = p_bi / p_fact / const_convert_atma_MPa

при обращении (получения) атрибута из класса, занового происходит расчет calc_PVT, значения свойств флюида могут поменяться (например, rs)

проблему удалось решить (или нет) с помощью

pb_atma_ = pb_calc_atma_ 'VFM

проблема возникла при создании функции PVT_all_pvt, которая считает все свойства один раз и выдает их 2 массивами (для валидации uniflocpy)

**Comment by khabibullinra** [comment]
поправил в ветке dev15

**Comment by khabibullinra** [comment]
в версии 15 исправление получилось плохое. если в расчете calc_PVT поменять давление насыщения pb_atma_ то возникают грабли в методах класса, которые могут вызывать расчет свойств PVT  несколько раз (например расчет Rp при котором достигается заданная доля газа в потоке).
поэтому в версии 16 будет такая логика

- исходное состояние класса CPVT не меняется при расчете - гарантирует что повторный расчет с теми же параметрами даст такой же результат 
- расчетное значение Pb и Rsb можно получить из свойств Pb_calc_atma и Rsb_calc_m3m3 доступных и снаружи класса
