### ISSUE TITLE
Поверхностное натяжение

### ISSUE THREAD

**Issue by kobzarius** [unifloc/unifloc_vba#35]
![image](https://user-images.githubusercontent.com/43096418/75560184-c0b48f00-5a55-11ea-9543-ee74b0ead3d8.png)

Ошибка в расчете поверхностного натяжения на границе нефть-газ

там еще стоит ' todo rnt20190312

**Comment by khabibullinra** [comment]
есть решение как поправить?

**Comment by khabibullinra** [comment]
Поправил ver 17
взял поправку отсюда  https://petrowiki.org/Interfacial_tension   eq(20)

![image](https://user-images.githubusercontent.com/30750735/78634970-d5ceda00-78ad-11ea-8da9-0a6c1f81731a.png)
