### ISSUE TITLE
Массовые расходы

### ISSUE THREAD

**Issue by kobzarius** [unifloc/unifloc_vba#36]
![image](https://user-images.githubusercontent.com/43096418/75606060-13e01d80-5afa-11ea-863c-0a551903da02.png)
Есть дублирование свойств массовых расходов по типу wwat_kgsec и mw_kgsec

Ненужный перевод в секунды в wliq_kgsec

 ' массовый расход жидкости при заданных термобарических условиях
 Public Property Get wliq_kgsec() As Double
    wliq_kgsec = wo_kgsec + wwat_kgsec ' VFM * const_conver_sec_day
 End Property

**Comment by khabibullinra** [comment]
поправил в dev15
