### ISSUE TITLE
Проблема python_api

### ISSUE THREAD

**Issue by Gregoryish** [unifloc/unifloc_vba#38]
Ошибки при вызове модуля **python_api**
    1. строка 333 функция MF_fit_pipe_m3day - кавычки в аргументах функции, а также при выводе (return).
    2. строка 2333, 2383, 2433, 2483 нарушен порядок последовательности аргументов по умолчанию и обязательных
    3. не объявлена переменная StartEndTemp.

**Comment by khabibullinra** [comment]
какая версия унифлока у вас? я вроде эти баги правил, в текущей версии все должно работать

**Comment by Gregoryish** [comment]
Всё в порядке! обновил репозиторий, ошибок больше нет.
