### ISSUE TITLE
В чем преимущество ESP базы данных в формате JSON?

### ISSUE THREAD

**Issue by AlexeyVodopyan** [unifloc/unifloc_vba#45]
Добрый день!

Пытаюсь понять почему JSON база данных насосов лучше, пока выводы такие

Плюсы JSON формата:
- нет дублирования параметров (например, когда идут точки НРХ, повторно не пишутся все остальные параметры), экономия размера файла
- все в одном формате (строки PVT, строки насосов, база), унифицирована работа с форматом

Минусы JSON формата:
- неудобно (в сравнении с обычной таблицей) добавлять насосы, в старой базе можно было открыть в экселе и безошибочно добавить новый насос

**Comment by AlexeyVodopyan** [comment]
Ринат Альфредович, поясните пожалуйста почему вы решили выбрать такой формат)

**Comment by AlexeyVodopyan** [comment]
Потенциально наверное удобнее из SQL получать данные в формате JSON и это тоже плюс

**Comment by khabibullinra** [comment]
У json формата по моему мнению есть ряд важных преимуществ:
- для работы с ним используется готовый класс и набор функций, что позволяет значительно упростить код. json сразу читается в словарь и потом с ним относительно просто работать. я наткнулся на эти библиотеки, когда пытался в строки для насосов добавить какую то фичу, и для этого довольно много правил алгоритм записи и чтения строк, а потом обнаружил, что с помощью json функций это делается в три строки кода и получается довольно универсально
- для работы с базой насосов есть отдельный excel файл, который умеет генерировать базу. Как раз было сделано чтобы унифицировать базу. Руками править большой файл грустно, поэтому лучше написать скрипт. Находится в папке db. Он же пример как работать с базой.
- удобство работы с json строками позволяет более гибко работать с выводом данных расчета на лист Excel  и эта фишка в последней версии используется и будет развиваться. Традиционно много времени у меня уходило на эксперименты как удобно выводить большие объемы данных. И вывод в виде json лучшее решение на текущий момент. Отсюда же должна быть простота обмена со скриптами на других языках.

**Comment by AlexeyVodopyan** [comment]
Добрый день
Спасибо, Ринат Альфредович!
В python-версии тоже стали использовать json-формат базы насосов, пандасом с ними работать удобнее, чем с таблицами, + в целом такой формат очень удобен для любых исходных данных в Python - можно подавать аргументы в виде словарей с распаковкой
