### ISSUE TITLE
Проблема удобного вывода данных из таблиц с json строками

### ISSUE THREAD

**Issue by kobzarius** [unifloc/unifloc_vba#47]
В таблице вывода по некоторым расчетам хранятся json строки, которые нужно разворачивать. (ESP_p_atma) Придумать метод удобной работы с данными, чтобы можно было строить графики методом "протяжки"

**Comment by khabibullinra** [comment]
есть идеи как это можно сделать?
для какого по параметра ставить флаг чтобы он выводился не как json?
