### ISSUE TITLE
Неточность перевода единиц в корреляции для вязкости дегазированной нефти

### ISSUE THREAD

**Issue by AlexeyVodopyan** [unifloc/unifloc_vba#48]
В функции unf_pvt_viscosity_dead_oil_Beggs_Robinson_cP в оригинальной корреляции идет перевод из кельвинов в фаренгейты, в функции он записан как (1.8 * Temperature_K - 460), хотя правильным будет (1.8 * Temperature_K - 459.4). Авторами указано диапазоны плотности для корреляции до 16 градусов API (~0.95) и при увеличении плотности ошибка из-за перевода единиц измерения может накапливаться значительная, тк в дальнейшем еще по ней расчитывается плотность газированной нефти и в некоторых случаях (выше насыщения)

**Comment by AlexeyVodopyan** [comment]
При высоких газовых факторах мало заметно, но при гф =5 м3/м3 получилась 10 атм ошибка на устье при расчете с забоя

**Comment by khabibullinra** [comment]
да надо будет поправить. Там где то были функции перевода размерностей - было бы правильно сделать чтобы все другие функции их использовали, тогда можно будет проще править точности при необходимости. этот баг я поправлю

**Comment by khabibullinra** [comment]
поправил вызвав UC_Temperature_K_to_F
