### ISSUE TITLE
убрать шероховатость

### ISSUE THREAD

**Issue by khabibullinra** [unifloc/unifloc_vba#52]
убрать шероховатость как отдельный параметр - добавив ее в массив диаметров

**Comment by AAGaleev** [comment]
Ринат Альфредович, приветствую! В функции расчета градиента unf_AnsariGradient площадь трубы вычисляется таким образом: Ap_m2 = const_Pi * arr_d_m ^ 2 / 4. Но т.к. параметр arr_d_m - это просто разница диаметров, то для расчета в затрубном пространстве правильнее будет: Ap_m2 = const_Pi * (Dcas^2 - Dtube^2) / 4.
