### ISSUE TITLE
Ошибка в расчете вязкости смеси

### ISSUE THREAD

**Issue by AlexeyVodopyan** [unifloc/unifloc_vba#54]
mu_mix_cP_ = (mu_oil_cP_ * q_oil_rc_m3day_ / qliq_rc_m3day_ + _
                      mu_wat_cP_ * q_wat_rc_m3day_ / qliq_rc_m3day_) * (1 - gas_fraction_d_) + _
                      mu_gas_cP_ * (1 - gas_fraction_d_)

ошибка в домножении вязкости газа на 1-gas_fract, нужно на gas_fract

**Comment by khabibullinra** [comment]
поправил в версии 7.26, спасибо
