### ISSUE TITLE
Ошибка в расчете трения в корреляции Gray Modified

### ISSUE THREAD

**Issue by AlexeyVodopyan** [unifloc/unifloc_vba#55]
При расчете псевдошероховатости в методике используется абсолютная шероховатость, и рассчитывается тоже абсолютная, которую нужно поделить на диаметр перед расчетом трения

Текущий фрагмент кода:
    e = roughness_d
    E1 = 28.5 * sigma_l_Nm / (Rho_n_kgm3 * Vsm_msec ^ 2)
    If r >= 0.007 Then e = E1
    If r < 0.007 Then e = e + r * (E1 - e) / 0.007  ' corrected error by Kiyan Artem from /0.0007
    crit = 2.8
    Nv = Rho_n_kgm3 ^ 2 * Vsm_msec ^ 4 / (const_g * sigma_l_Nm * (rho_lrc_kgm3 - rho_grc_kgm3))
    Nd = const_g * (rho_lrc_kgm3 - rho_grc_kgm3) * d_m ^ 2 / sigma_l_Nm
    
    b = 0.0814 * (1 - 0.0554 * Log(1 + 730 * r / (r + 1)))
    h_l = (r + Exp(-2.314 * (Nv * (1 + 250 / Nd)) ^ b)) / (r + 1)
    'Calculate normalized friction factor
    f_n = unf_friction_factor(n_re, e, Payne_et_all_friction)

Предлагаемый фрагмент кода:

    E1 = 28.5 * sigma_l_Nm / (Rho_n_kgm3 * Vsm_msec ^ 2)
    If r >= 0.007 Then e = E1
    If r < 0.007 Then e = eps_m + r * (E1 - eps_m) / 0.007  ' corrected error by Kiyan Artem from /0.0007

    crit = 2.8
    Nv = Rho_n_kgm3 ^ 2 * Vsm_msec ^ 4 / (const_g * sigma_l_Nm * (rho_lrc_kgm3 - rho_grc_kgm3))
    Nd = const_g * (rho_lrc_kgm3 - rho_grc_kgm3) * d_m ^ 2 / sigma_l_Nm

    b = 0.0814 * (1 - 0.0554 * Log(1 + 730 * r / (r + 1)))
    h_l = (r + Exp(-2.314 * (Nv * (1 + 250 / Nd)) ^ b)) / (r + 1)

    'Calculate normalized friction factor
    roughness_d = e / d_m
    f_n = unf_friction_factor(n_re, roughness_d, Payne_et_all_friction)

**Comment by khabibullinra** [comment]
поправил
