### ISSUE TITLE
Реализовать PVT_mod_mix

### ISSUE THREAD

**Issue by khabibullinra** [unifloc/unifloc_vba#56]
Заготовка есть надо реализовать и сделать пример для проверки корректности расчета и раздел для мануала

смешение двух потоков флюидов

**Comment by Pulkinen** [comment]
Не-не, лучше по другому сделать.
Скалярное произведение вектора весов на вектор флюидов.
Смотри, когда у тебя несколкьо источников, то по каждому участку будет течь сколько-то флюида из перовго источника, сколько-то из второго итд. Тогда для описания что там течет, достаточно будет найти массовые потоки для флюида каждого источника. А для этой задачи у меня решение есть, только не выложено пока.

**Comment by khabibullinra** [comment]
Пока не очень понял, что имеется в виду. Но возможно потом тоже можно будет сделать для n флюидов.

Сейчас идея такая - что поток флюида, включая расходы и все параметры - это экземпляр класса CPVT и его можно описать конечным набором параметров, которые в частности можно сохранить в виде строки параметров.
И есть алгоритм который умеет смешивать два потока - то есть находить новый набор параметров, Если массовые расходы фаз там просто складываются, то эффективные значения других параметров (плотностей, газосодержаний и калибровочных параметров) определяюся сложнее (средние взвешенные, но не всегда). Поэтому просто перемножить расходы на веса не всегда сработает.
Тут должно относительно корретно сработать при смешении тяжелой и легкой нефти например.
Алгоритм уже есть у меня в виде таблицы Excel надо теперь его только в код перенести.

**Comment by Pulkinen** [comment]
Да, я понимаю что ты хочешь сделать.
Теперь взгляни на чуть более общую задачу. У тебя есть например 4 источника, из каждого идет жидкость своего цвета. Всё это попадает в какой-то сложный лабиринт из труб. В любой точке этого лабиринта, каждый атом текущей жидкости могу появится только из ровно одного из 4х источников.
Поэтому имеет смысл ввести линейную операцию над жидкостями. 
Fluid_mix = (x1/x_all, x2/x_all, x3/x_all, x4/x_all) * (Fluid1, Fluid2, Fluid3, Fluid4)
Этакое скалярное произведением над вектором весов и вектором жидкостей.
Понятно, что для плотности например, или для цвета, это и будет скалярное произведение, ну или что тоже самое средневзвешенный цвет/плотность.
Если у тебя Fluid - сложный объект,  с десятками параметров, то например вязкость смеси лучше считать как кубический корень суммы кубов вязкостей (или наоборот, могу путать. Это из пайпсима)
Еще сложнее всё становится если у тебя для параметров заданы калибровочные точки. Или еще пример из пайпсима - что если у этих жидкостей пользователем заданы разные корреляции на трение? Ее ж нельзя посчитать как средневзвешенную )

Но спич мой на самом деле про другое. Вычисление некоторых параметров может быть сложным, некоторых - простым. Но интерфейс к смешению стоит сделать в такой вот форме - "скалярное произведение" вектора весов на вектор жидкостей, возвращающее такой же объект жидкость.

Извини, сумбурно изложил, похоже температура поднялась, отхожу от ковида.

**Comment by Pulkinen** [comment]
Еще немного сумбура.
Смотри. Допустим ты сделаешь "бинарную" функцию смешения которая работает от двух жидкостей и двух весов. Принимает на вход два json-а жидкостей и выдает такой же джейсон.
Теперь пусть у нас сеть с десятком источников. Вот мы смотрим на какую-то трубу. Веса источников в смеси текущей по трубе - вполне определенные. Но при этом джейсон этой смеси, расчитаной "бинарной" функцией смешения может получится разный, в зависимости от того каким деревом из "бинарных" функций смешения он был получен. Результат вычисления будет зависеть не только от аргумента, но и от графа вычислений.

**Comment by Pulkinen** [comment]
Понятно что плотность, которая считается как средневзвешенная, не будет зависеть от графа вычислений. Но ты устанешь это гарантировать для более сложно вычисляемых параметров.

**Comment by khabibullinra** [comment]
если сделать алгоритм смешения двух флюидов, то функция скалярного произведения, которую ты предлагаешь, сделать будет легко. Я сделаю такую.
Но при этом вопрос о зависимости от графа смешиваемости останется. 
Как я вижу это хорошая задача для какого нить студента. Унифлок позволит решать такую задачу, но не должен содержать в себе готового решения

**Comment by khabibullinra** [comment]
бинарное смешение вроде как то сделано
